[DEFAULT]
# This tells Yoyo where to look for our SQL scripts
sources = migrations

# This is your database connection URL
database = postgresql://postgres:sarvesh@localhost/rk_trendz_mlm

# Standard execution settings
batch_mode = off
verbosity = 2
